# Generated by Django 5.1.1 on 2024-09-18 08:07

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.managers.CustomUserManager()),
            ],
        ),
    ]
