# Generated by Django 5.1.1 on 2024-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
